aws configservice put-config-rule --cli-input-json file://access-keys-rotated.json --profile x --region cc-reg-nbr
aws configservice put-config-rule --cli-input-json file://access-keys-rotated.json --profile x-ops --region cc-reg-nbr
aws configservice put-config-rule --cli-input-json file://access-keys-rotated.json --profile x-dev --region cc-reg-nbr
aws configservice put-config-rule --cli-input-json file://access-keys-rotated.json --profile x-security --region cc-reg-nbr
aws configservice put-config-rule --cli-input-json file://access-keys-rotated.json --profile x-marketing --region cc-reg-nbr
aws configservice put-config-rule --cli-input-json file://access-keys-rotated.json --profile x-swd-tools --region cc-reg-nbr
aws configservice put-config-rule --cli-input-json file://access-keys-rotated.json --profile x-swd-master --region us-east-1
aws configservice put-config-rule --cli-input-json file://access-keys-rotated.json --profile x-prod --region cc-reg-nbr
aws configservice put-config-rule --cli-input-json file://access-keys-rotated.json --profile x-dev --region cc-reg-nbr
